### ISSUE TITLE
NAMI.py: Extra row over A1 in the heat map

### ISSUE THREAD

**Issue by agabee** [grofte/NAMI#3]
Hi, 

I am getting an extra grey coloured row over the A1-12 row in the heat map (heat map itself looks correct and contains all of the values, but the sol contents/buffer compositions are also messed up and show up in the empty grey area). I was wandering wether it's an easy problem to solve (i.e. raw data in wrong format etc.)? I would be very grateful or any help on that, the software is awesome. 

Thanks, 
A.

**Comment by grofte** [comment]
That is a good question. I don't see any way to message you directly on Github but if you go to https://twitter.com/DrGroftehauge then you can direct message me and we can exchange emails and sort this out. I can understand why you might not want to post your data here ;)

**Comment by grofte** [comment]
Okay, I have made executables for Linux, Mac, and Windows years ago but Durham didn't want to host them on their website. I sent one to agabee and it resolved the issue. I am going to add a link to my Twitter account to the README and anyone can contact me directly. If anyone has a suggestion for where and how to host executables in a safe manner please contact me.
